Add requests dependency
HarlemSquirrel/python-vivotek pull request #12
Opened 2022-08-15 09:49 UTC by jenhaoyang

Add requests dependency

2022-08-29 19:03 UTC, HarlemSquirrel requested changes
Thank you for opening this PR! 

I would like to set a minimum version here since I haven't tested this with any earlier versions of requests.

2022-08-29 19:03 UTC, HarlemSquirrel commented on setup.py
> +        'requests',
```suggestion
        'requests >= 2.21',
```

2022-08-30 04:42 UTC, jenhaoyang commented on setup.py
> +        'requests',
No problem

2022-08-30 10:40 UTC, HarlemSquirrel approved these changes
Thank you!

2022-08-30 10:40 UTC, merged